services:
  - type: web
    name: ecovision-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python train_on_start.py && gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: false
